[package]
name = "aptos-runtime"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos Runtime utilities"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }

once_cell = "1.10.0"
tokio = { version = "1.18.2", features = ["full"] }
tokio-metrics = { version = "0.1.0", default-features = false, features = ["rt"] }



