[package]
name = "aptos-transaction-builder"
version = "0.0.3"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Generated transaction builders"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.3"
once_cell = "1.10.0"
proptest-derive = { version = "0.3.0", optional = true }

aptos-types = { path = "../../types" }

framework = { path = "../../aptos-move/framework" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"

move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "fuzzing"] }

[features]
default = []
fuzzing = ["proptest-derive", "framework/fuzzing", "move-deps/fuzzing"]
